language: node_js

node_js:
  - stable
  - "8"
  - "10"
  - "12"

install:
  - npm install

script:
  - npm test

notifications:
  email: false

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
