name: Publish packages

on:
  release:
    types: [published]

concurrency:
  group: publish-${{ github.event.release.tag_name }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    if: github.event.release.prerelease == false
    uses: ./.github/workflows/build.yml
    with:
      release-tag: ${{ github.event.release.tag_name }}

  publish-to-npm:
    name: Stage package on npm
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '26'
          registry-url: 'https://registry.npmjs.org'
          scope: '@luanmuniz'
          package-manager-cache: false
      - run: npm stage publish

  publish-to-github:
    name: Publish package to GitHub Packages
    needs: publish-to-npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '26'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@luanmuniz'
          package-manager-cache: false
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
